cloth_shop/api/urls.py
from django.urls import include, path
from rest_framework import routers

from api.views import *

urlpatterns = [
    path('customers/', Customers.as_view()),
    path('customers/<int:user>', Customers_detail.as_view()),

    path('genders/', Genders.as_view()),
    path('big_category/', Big_Category.as_view()),
    path('category/', CategoryView.as_view()),

    path('product/',ProductView.as_view()),
    path('product/<int:category>', product_detail.as_view()),

    path('product/slug/<str:slug>', product_detail_slug.as_view()),



    path('reviewlist/',ReviewListView.as_view()),
    path('reviewlist/<int:customer>',reviewlist_detail.as_view()),

    path('reviewitem/',ReviewItemView.as_view()),

    path('address/',AddressView.as_view()),
    path('address/<int:user>',address_detail.as_view()),

    path('cart/',CartView.as_view()),
    path('cart/<int:customer>',cart_detail.as_view()),

    path('cartproduct/',CartProductView.as_view()),    

    #path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

cloth_shop/cloth_shop/urls.py
from django.contrib import admin
from django.urls import include, path
from store import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('store.urls')),
    path('', views.home, name = "home"),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special,name='special'),
    path('api/', include('api.urls')),
    path("admin-login/", views.AdminLoginView.as_view(), name="adminlogin"),


]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)




#My Comment

cloth_shop/store/urls.py
from django.urls import include, path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.home, name = "home"),
    path('store/', views.store, name = "store"),
    path('womenPage/', views.womenPage, name ="womenPage"),



    path('search/', views.SearchView.as_view(), name = "search"),
    path('price-low-to-high/', views.OrderByPriceAs.as_view(), name ="price"),
    path('price-high-to-low/', views.OrderByPriceDes.as_view(), name ="priceDes"),
    path('popularity-low-to-high/', views.OrderByPopularityAs.as_view(), name ="popularityAs"),
    path('popularity-high-to-low/', views.OrderByPopularityDes.as_view(), name ="popularityDes"),
    # path("rate-<int:pro_id>/'", views.CommentView.as_view(), name="rate"),



    path('add_to_cart-<int:pro_id>/', views.AddToCart.as_view(), name = "AddToCart"),
    path('myBasket/', views.myBasketView.as_view(), name ="myBasket"),
    path("manage-cart/<int:cp_id>/", views.ManageCartView.as_view(), name = "managecart"),
    path("checkout/", views.CheckoutView.as_view(), name="checkout"),
    path('myOrders/', views.CustomerOrdersView.as_view(), name ="myOrders"),
    path('cancelOrder<int:pk>', views.CustomerCancelOrdersView.as_view(), name ="cancelOrder"),
    path('myProfile/', views.CustomerProfileView.as_view(), name ="myProfile"),
    path("orderDetails/order-<int:pk>/", views.CustomerOrderDetailView.as_view(),name="customerorderdetail"),
    path('rate-<int:pro_id>/', views.AddToReviewList.as_view(), name ="rate"),
    path("receipt/order-<int:pk>/", views.CustomerReceiptView.as_view(),name="receipt"),
    path("receipt/sendmail/<int:id>", views.SendEmail, name="SendEmail"),
    path('payment/', views.CustomerPaymentView.as_view(), name ="payment"),
    path('myRatingsEvaluated/', views.CustomerReviewView.as_view(), name ="myRatingsEvaluated"),
    path('productReviews/-<int:pk>/', views.ProductReviewView.as_view(), name ="productReviews"),
    path('add_to_wishlist-<int:pro_id>/', views.AddToWishList.as_view(), name = "AddToWishList"),
    path('myWishList/', views.myWishListView.as_view(), name ="myWishList"),
    path('myWishRemove-<int:obj_id>//', views.myWishRemoveView.as_view(), name ="myWishRemove"),



    # PRODUCT MANAGERS URLS
    path("admin-home/", views.productmanagersHome, name="productmanagersHome"),
    path("admin-login/", views.AdminLoginView.as_view(), name="adminlogin"),
    path("admin-PendingOrders/", views.AdminPendingOrdersView.as_view(), name="adminPendingOrders"),
    path("admin-order/<int:pk>/", views.AdminOrderDetailView.as_view(), name="adminorderdetail"),
    path("admin-all-orders/", views.AdminOrderListView.as_view(), name="adminorderlist"),
    path("admin-order-<int:pk>-change/",views.AdminOrderStatusChangeView.as_view(), name="adminorderstatuschange"),
    path("admin-pendingComment/", views.PendingReviewView.as_view(), name="adminpendingComment"),
    path("admin-all-reviews/", views.AdminReviewListView.as_view(), name="adminreviewlist"),
    path("admin-detailComment/<int:pk>/", views.AdminReviewDetailView.as_view(), name="admindetailComment"),
    path("admin-review-<int:pk>-change/",views.AdminReviewStatusChangeView.as_view(), name="adminreviewstatuschange"),
    path("admin-product-list/", views.AdminProductListView.as_view(), name="adminproductlist"),
    path("admin-product-add/", views.AdminProductCreateView.as_view(), name="adminproductcreate"),
    path("admin-productdelete/<int:pr_id>/", views.AdminProductDeleteView.as_view(), name = "adminproductdelete"),
    path("admin-category-list/", views.AdminCategoryListView.as_view(), name="admincategorylist"),
    path("admin-category-add/", views.AdminCategoryCreateView.as_view(), name="admincategorycreate"),
    path("admin-categorydelete/<int:c_id>/", views.AdminCategoryDeleteView.as_view(), name = "admincategorydelete"),
    path("admin-PendingRefundRequests/", views.AdminPendingRefundRequestsView.as_view(), name="adminRefundRequests"),
    path("admin-AllRefundRequests/", views.AdminAllRefundRequestsView.as_view(), name="adminAllRefundRequests"),
    path('product_managers_logout/', views.product_managers_logout, name='product_managers_logout'),
    path('product_managers_stock/<int:pk>/', views.AdminProductStockChangeView.as_view(), name='product_managers_stock'),
    # END OF PRODUCT MANAGERS URLS

    #  SALES MANAGERS URLS
    path("sales-admin-home/", views.salesmanagersHome, name="salesmanagersHome"),
    path("admin-sales-order/<int:pk>/", views.AdminSalesOrderDetailView.as_view(), name="adminsalesorderdetail"),
    path("sales-admin-login/", views.SalesAdminLoginView.as_view(), name="SalesAdminLoginView"),
    path("sales-admin-products/", views.SalesAdminProductListView.as_view(), name="SalesAdminProductListView"),
    path("sales-price-update/<int:id>/change", views.SalesAdminChangePrice, name="SalesAdminChangePrice"),
    path("price_updated/", views.PriceUpdatedView.as_view(), name="PriceUpdatedView"),
    path("sales-show-invoices/", views.SalesShowInvoices.as_view(), name="SalesShowInvoices"),
    path("invoice-pdf/<int:id>", views.ShowPDF, name="ShowPDF"),
    path("sales-show-profit/", views.SalesShowProfit.as_view(), name="SalesShowProfit"),
    path('sales_managers_logout/', views.sales_managers_logout, name='sales_managers_logout'),
    path('sales_managers_price/<int:pk>/', views.AdminProductPriceChangeView.as_view(), name='sales_managers_price'),

    # END OF SALES MANAGERS URLS


    path('otherCategories/', views.OtherCategoryListView.as_view(), name ="OtherCategoryListView"),
    path('allProducts/', views.AllListView.as_view(), name ="AllListView"),
    path('womenDressPage/', views.DressListView.as_view(), name ="DressListView"),
    path('productDetail/<slug>/', views.ProductDetailView.as_view(), name ="productDetail"),
    path('womenSkirtPage/', views.SkirtListView.as_view(), name ="SkirtListView"),
    path('womenSweatshirtPage/', views.SweatshirtListView.as_view(), name ="SweatshirtListView"),
    path('womenBlousesPage/', views.BlousesListView.as_view(), name ="BlousesListView"),
    path('womenSweaterPage/', views.SweaterListView.as_view(), name ="SweaterListView"),
    path('womenTshirtPage/', views.TshirtListView.as_view(), name ="TshirtListView"),
    path('womenCoatPage/', views.CoatListView.as_view(), name ="CoatListView"),
    path('womenSleepPage/', views.SleepListView.as_view(), name ="SleepListView"),
    path('womenShortPage/', views.ShortListView.as_view(), name ="ShortListView"),
    path('womenPantPage/', views.PantListView.as_view(), name ="PantListView"),
    path('womenSweatsuitPage/', views.SweatsuitListView.as_view(), name ="SweatsuitListView"),



    path('user_login/',views.user_login,name='user_login'),
    path('register/', views.register, name ="register"),
    path('myRatings/', views.myRatings, name ="myRatings"),
    path('wishlist/', views.wishlist, name ="wishlist"),


    path('request-refund/order-<int:ord_id>/', views.RequestRefundView.as_view(), name='request-refund'),
    path('grant-refund/orderProduct-<int:orderP_id>/', views.GrantRefundView.as_view(), name='grant-refund')
]

cloth_shop/store/forms.py
from django import forms
from django.contrib.auth.models import User
from django import forms
from .models import Order, OrderProduct
from .models import ReviewItem
from .models import Product
from .models import Category
from django.core.files.uploadedfile import SimpleUploadedFile

# from django_countries.fields import CountryField
# from django_countries.widgets import CountrySelectWidget


class CheckoutForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ["ordered_by", "shipping_address",
                  "email", "payment_method"]


class ProductManagersLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())
    distributor = forms.Select()

class SalesManagersLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())

class PriceChangeForm(forms.Form):

    discount = forms.IntegerField(label='Discount rate')




class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')


class ReviewItemForm(forms.ModelForm):
	class Meta:
		model = ReviewItem
		fields = ["comment", "rate"]

class ContactForm(forms.Form):
    name= forms.CharField(max_length=500, label="Name")
    email= forms.EmailField(max_length=500, label="Email")
    comment= forms.CharField(label='',widget=forms.Textarea(
                        attrs={'placeholder': 'Enter your comment here'}))


class StockForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [ "quantity"]
        widgets = {
            "quantity": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Enter the new quantity in stock..."
            }),

        }


class PriceForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [ "price"]
        widgets = {
            "price": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Enter the new price..."
            }),

        }


class ProductForm(forms.ModelForm):
    more_images = forms.FileField(required=False, widget=forms.FileInput(attrs={
        "class": "form-control",
        "multiple": True
    }))

    class Meta:
        model = Product
        fields = ["name", "gender",  "slug", "category", "Primaryimage", "Secondimage", "Thirdimage", "model", "warrantyStatus",
                   "color", "quantity", "popularity", "price", "description"]
        widgets = {
            "name": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Enter the product title here..."
            }),
            "slug": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Enter the unique slug here..."
            }),
            "gender": forms.Select(attrs={
                "class": "form-control",
            }),
            "category": forms.Select(attrs={
                "class": "form-control"
            }),
             "Primaryimage": forms.FileInput(attrs={
                 "class": "form-control"
             }),
             "Secondimage": forms.ClearableFileInput(attrs={
                 "class": "form-control"
             }),
            "Thirdimage": forms.ClearableFileInput(attrs={
                 "class": "form-control"
             }),
             "price": forms.NumberInput(attrs={
                "class": "form-control",
                "placeholder": "Marked price of the product..."
             }),
            "model": forms.TextInput(attrs={
                "class": "form-control",
            }),
            "description": forms.Textarea(attrs={
                "class": "form-control",
                "placeholder": "Description of the product...",
                "rows": 5
            }),
            "warrantyStatus": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Enter the product warranty here..."
            }),
            "color": forms.TextInput(attrs={
                "class": "form-control",

            }),
            "quantity": forms.TextInput(attrs={
                "class": "form-control",

            }),
            "popularity": forms.TextInput(attrs={
                "class": "form-control",

            }),



         }

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ["name", "slug", "bigcategory" ]
        widgets = {
            "bigcategory": forms.Select(attrs={
                "class": "form-control",
            }),
            "name": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Enter the product title here..."
            }),
            "slug": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Enter the unique slug here..."
            }),

         }

class DateForm(forms.ModelForm):
    start_date = forms.DateTimeField()
    end_date = forms.DateTimeField()
    class Meta:
        model = Order
        fields = []


# class UserProfileInfoForm(forms.ModelForm):
#     class Meta():
#         model = Customer
#         fields = ('adress1','adress2')

cloth_shop/store/templates/store/allProducts.html
{% extends 'store/womenNavbar.html' %}
{% load static %}





{% block content_AllPage %}
<div class="container">
  <div class="wtitle1">
    <h2> All Products Page </h2>
  </div>



  <div class="row">
    {% for item in object_list %}
    <div class="col-lg-3">
         <a href="{{item.get_absolute_url}}">
         <img src= {{item.Primaryimage.url}} alt="Dress1 alternative" class="dress">
         </a>

        <a href="{{item.get_absolute_url}}">
         <p class="dress_text"> {{item.name}}
        </a>
      <br>

      Price: <span class="price">${{item.price}}</span>




    </div>
    {% endfor %}
  </div>


</div>

{% endblock  %}

cloth_shop/store/templates/store/myProfile.html
{% extends 'store/base.html' %}
{% load static %}

{% block content_SideBar-order %}
<div class="sidebar">
  <a class="" href="{% url 'store:myOrders' %}">My Orders</a>
  <a href="{% url 'store:myRatingsEvaluated' %}">My ratings</a>
  <a href="{% url 'store:myProfile' %}">My User Information</a>

</div>
{% endblock %}

{% block order-page %}
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h3>Detail Information</h3><hr>
            <p><span class="font-weight-bold">Name: </span> {{customer.full_name}}</p>
            <p><span class="font-weight-bold">Username: </span> {{customer.user.username}}</p>
            <p><span class="font-weight-bold">Email: </span> {{customer.user.email}}</p>
            <p><span class="font-weight-bold">Address: </span> {{customer.address}}</p>
            <p><span class="font-weight-bold">Joined on: </span> {{customer.joined_on}}</p>
        </div>

    </div>
</div>
{% endblock %}

cloth_shop/store/templates/store/myWishList.html
{% extends 'store/base.html' %}
{% load static %}
{% block content_mainPage %}


<div class="">
	<div class="container">
		<h5 class="fw-bold">
			<a href="{% url 'store:womenPage' %}"><i class="fas fa-angle-left me-2"></i>Back to shopping</a>
		</h5>


		<div class="row">
			<div class="col-md-12">
				<!-- <div class="main-heading mb-10  ">Your Wish List</div> -->
				<h2 class="mb-5 pt-2 text-center fw-bold   ">Your Wish List</h2>

				<div class="table-wishlist">
					<table cellpadding="0" cellspacing="0" border="0" width="100%">
						<thead>
							<tr>
								<th width="45%">Product Name</th>
								<th width="15%">Unit Price</th>
								<th width="15%">Stock Status</th>
								<th width="15%"></th>
								<th width="10%"></th>
							</tr>
						</thead>

						{% for wishobj in wishlist.wishitem_set.all %}
						<tbody>
							<tr>
								<td width="45%">
									<div class="display-flex align-center">
										<div class="img-product">
											<img src="{{wishobj.product.Primaryimage.url}}" alt=" a" class="mCS_img_loaded">
										</div>
										<div class="name-product">
											{{wishobj.product.name}}
										</div>
									</div>
								</td>
								<td width="15%" class="price"> {{wishobj.product.price}}</td>
								<td width="15%"><span class="in-stock-box">
										{{wishobj.product.quantity}}
									</span></td>

								<!-- <td width="15%"><button class="round-black-btn small-btn">Add to Cart</button></td> -->

								{% if wishobj.product.quantity == 0 %}
								<td width="15%"><button class="round-black-btn small-btn">OUT OF STOCK</button></td>
								{% else %}
								<td width="15%"><button class="round-black-btn small-btn">
										<a href="{% url 'store:AddToCart' wishobj.product.id %}">
											ADD TO CART
										</a> </button></td>
								{% endif %}
								<td width="10%" class="text-center"><a href="{% url 'store:myWishRemove' wishobj.id %}" class="trash-icon">
									<i class="far fa-trash-alt"></i></a></td>

						</tbody>
						{% endfor %}
					</table>
				</div>
			</div>
		</div>
	</div>
</div>




{% endblock %}

cloth_shop/store/templates/store/store.html
{% extends 'store/base.html' %}
{% load static %}
{% block content %}
     <h3>store</h3>
{% endblock content %}

cloth_shop/store/templates/store/womenNavbar.html
<!doctype html>
{% load static %}
{% load cart_template_tags %}
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />
  <link rel="stylesheet" href="{% static "css/womenNavbar.css" %}" />
  <link rel="stylesheet" href="{% static "css/womenDress.css" %}" />
  <link rel="stylesheet" href="{% static "css/product.css" %}" />
  <link rel="stylesheet" href="{% static "css/womenPage.css" %}" />

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  <title>trendSU</title>

  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/468cba9b63.js" crossorigin="anonymous"></script>

</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <img class="trendSU2" src="{% static "images/trendSU2.png" %}" alt="logo">
      <a class="navbar-brand" style="position: relative;right: 80px;">trend<span class="SU">SU</span></a>

      <ul class="navbar-nav" style="position: relative;right: 150px;">
        <li class="gender_nav nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'store:womenPage' %}">Women</a>
        </li>

      </ul>
      <form class="d-flex" action = " {% url 'store:search' %}" method = "GET" >
        <input class="form-control me-2 search_form" style="width: 300px;" type="text"  aria-label="Search" name = "keyword" placeholder="Search" required>
        <button class="search_btn btn btn-outline-success" type="submit">Search</button>
      </form>

      <ul class="navbar-nav" >
        <li class="second-items nav-item dropdown">
          <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fas fa-user"></i> My Account
          </a>
          <ul class=" dropdown-menu" aria-labelledby="navbarDropdown">
            {% if user.is_authenticated %}
            <li class="my_account">
              <div class="d-grid gap-2 col-10 mx-auto">
                <a href="{% url 'store:myOrders' %}" class="btn btn-dark btn-sm" role="button"> MY ORDERS </a></a>

              </div>
            </li>
            <li class="my_account">
              <div class="d-grid gap-2 col-10 mx-auto">
                <a href="{% url 'store:myRatingsEvaluated' %}" class="btn btn-dark btn-sm" role="button"> MY EVALUATIONS </a></a>

              </div>
            </li>
            <li class="my_account">
              <div class="d-grid gap-2 col-10 mx-auto">
                <a href= "{% url 'store:myProfile' %}" class="btn btn-dark btn-sm" role="button"> MY PROFILE </a></a>

              </div>
            </li>
            <li class="my_account">
              <div class="d-grid gap-2 col-10 mx-auto">
                <a href="{% url 'logout' %}" class="btn btn-dark btn-sm" role="button"> LOGOUT </a></a>

              </div>
            </li>
            {% else %}
            <li class="my_account">
              <div class="d-grid gap-2 col-10 mx-auto">
                <a href="{% url 'store:user_login' %}" class="btn btn-dark btn-sm" role="button"> LOG IN </a></a>

              </div>
            </li>
            <li class="my_account">
              <div class=" d-grid gap-2 col-10 mx-auto">
                <a href="{% url 'store:register' %}" class="btn btn-light btn-sm" role="button"> REGISTER</a></a>

              </div>
            </li>
            {% endif %}
          </ul>
        </li>
        <li class="second-items nav-item">
          <a class="star information nav-link active" href="{% url 'store:myWishList' %}">
             <i class="fas fa-heart"></i> Wishlist </a>
        </li>
        <li class="second-items nav-item">
          <a class="information nav-link active" href="{% url 'store:myBasket' %}">

            <i class="fas fa-basket-shopping"></i> My Basket </a>
        </li>
      </ul>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </nav>



  <!-- Women Navbar -->
  <nav class="second_navbar_women navbar navbar-expand-lg navbar-light bg-light">
    <div class="women_navbar_cont container-fluid">
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="secondNav navbar-nav">
          <li class="second-items nav-item">
              <a class="star information nav-link active" href="{% url 'store:AllListView' %}"> All Products</a>
          </li>
          <li class="women_li nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Clothing
            </a>
            <ul class="women_dropdown_clothes dropdown-menu" aria-labelledby="navbarDropdown">
              <div class="row">
                <div class="col-lg-6">

                  <li><a class="dropdown-item" href="{% url 'store:DressListView' %}">Dresses</a></li>
                  <li><a class="dropdown-item" href="{% url 'store:SweatshirtListView' %}">Sweatshirts</a></li>
                  <li><a class="dropdown-item" href="{% url 'store:BlousesListView' %}">Blouses&Shirts</a></li>
                  <li><a class="dropdown-item" href="{% url 'store:SweaterListView' %}">Sweater</a></li>
                  <li><a class="dropdown-item" href="{% url 'store:TshirtListView' %}">T-shirts</a></li>
                  <li><a class="dropdown-item" href="{% url 'store:CoatListView' %}">Coats&Jackets</a></li>


                </div>
                <div class="col-lg-6">
                  <li><a class="dropdown-item" href="{% url 'store:SkirtListView' %}">Skirts</a></li>
                  <li><a class="dropdown-item" href="{% url 'store:SleepListView' %}">SleepWear</a></li>
                  <li><a class="dropdown-item" href="{% url 'store:ShortListView' %}">Shorts&Bermuda</a></li>
                  <li><a class="dropdown-item" href="{% url 'store:PantListView' %}">Pants&Jeans</a></li>
                  <li><a class="dropdown-item" href="{% url 'store:SweatsuitListView' %}">Sweatsuit</a></li>

                </div>

              </div>
            </ul>
          </li>
          <li class="women_li nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Tops
            </a>
            <ul class="women_dropdown_tops dropdown-menu" aria-labelledby="navbarDropdown">
              <div class="row">
                <div class="col-lg-12">
                  <li><a class="dropdown-item" href="{% url 'store:SweatshirtListView' %}">Sweatshirts</a></li>
                  <li><a class="dropdown-item" href="{% url 'store:BlousesListView' %}">Blouses&Shirts</a></li>
                  <li><a class="dropdown-item" href="{% url 'store:SweaterListView' %}">Sweater</a></li>
                  <li><a class="dropdown-item" href="{% url 'store:TshirtListView' %}">T-shirts</a></li>
                  <li><a class="dropdown-item" href="{% url 'store:CoatListView' %}">Coats&Jackets</a></li>
                </div>
              </div>
            </ul>
          </li>
          <li class="women_li nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
             Bottoms
            </a>
            <ul class="women_dropdown_pants dropdown-menu" aria-labelledby="navbarDropdown">
              <div class="row">
                <div class="col-lg-12">
                  <li><a class="dropdown-item" href="{% url 'store:ShortListView' %}">Shorts</a></li>
                  <li><a class="dropdown-item" href="{% url 'store:PantListView' %}">Pants & Jeans</a></li>
                  <li><a class="dropdown-item" href="{% url 'store:SkirtListView' %}">Skirts</a></li>
                  <li><a class="dropdown-item" href="{% url 'store:SweatsuitListView' %}">Sweatsuit</a></li>


                </div>
              </div>
            </ul>
          </li>


          <div class="header-bottom-set dropdown" style="position: absolute;right: 75px;top: 20px;">
            <button class = "dropdown-toggle header-action-btn" data-bs-toggle= "dropdown">Default <i class ="fas fa-angle-down"></i></button>
            <ul class="dropdown-menu dropdown-mun-right">
                <li><a class="dropdown-item" name = "keyword" href="{% url 'store:priceDes' %}">Price, high-to-low</a></li>
                <li><a class="dropdown-item" name = "keyword" href="{% url 'store:price' %}">Price, low-to-high</a></li>
                <li><a class="dropdown-item" name = "keyword" href="{% url 'store:popularityDes' %}">Most popular</a></li>
                <li><a class="dropdown-item"  name = "keyword" href="{% url 'store:popularityAs' %}">Least populars</a></li>
            </ul>
          </div>

          <li class="second-items nav-item">
              <a class="star information nav-link" href="{% url 'store:OtherCategoryListView' %}">Others</a>
          </li>

        </ul>
      </div>
    </div>
  </nav>

  {% block content_womenPage %}
  {% endblock %}

  <div class="row">
    <div class="col-lg-2">
      {% block content_SideBar %}
      {% endblock %}
    </div>
    <div class="col-lg-10">
      {% block content_Page %}
      {% endblock %}
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      {% block content_product %}
      {% endblock %}
    </div>
  </div>

  {% block content_AllPage %}
  {% endblock %}




</body>

</html>