cloth_shop/api/urls.py
from django.urls import include, path
from rest_framework import routers

from api.views import *

urlpatterns = [
    path('customers/', Customers.as_view()),
    path('customers/<int:user>', Customers_detail.as_view()),

    path('genders/', Genders.as_view()),
    path('big_category/', Big_Category.as_view()),
    path('category/', CategoryView.as_view()),

    path('product/',ProductView.as_view()),
    path('product/<int:category>', product_detail.as_view()),

    path('product/slug/<str:slug>', product_detail_slug.as_view()),



    path('reviewlist/',ReviewListView.as_view()),
    path('reviewlist/<int:customer>',reviewlist_detail.as_view()),

    path('reviewitem/',ReviewItemView.as_view()),

    path('address/',AddressView.as_view()),
    path('address/<int:user>',address_detail.as_view()),

    path('cart/',CartView.as_view()),
    path('cart/<int:customer>',cart_detail.as_view()),

    path('cartproduct/',CartProductView.as_view()),    

    #path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

cloth_shop/cloth_shop/urls.py
from django.contrib import admin
from django.urls import include, path
from store import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('store.urls')),
    path('', views.home, name = "home"),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special,name='special'),
    path('api/', include('api.urls')),
    path("admin-login/", views.AdminLoginView.as_view(), name="adminlogin"),


]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)




#My Comment

cloth_shop/store/urls.py
from django.urls import include, path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.home, name = "home"),
    path('store/', views.store, name = "store"),
    path('womenPage/', views.womenPage, name ="womenPage"),



    path('search/', views.SearchView.as_view(), name = "search"),
    path('price-low-to-high/', views.OrderByPriceAs.as_view(), name ="price"),
    path('price-high-to-low/', views.OrderByPriceDes.as_view(), name ="priceDes"),
    path('popularity-low-to-high/', views.OrderByPopularityAs.as_view(), name ="popularityAs"),
    path('popularity-high-to-low/', views.OrderByPopularityDes.as_view(), name ="popularityDes"),
    # path("rate-<int:pro_id>/'", views.CommentView.as_view(), name="rate"),



    path('add_to_cart-<int:pro_id>/', views.AddToCart.as_view(), name = "AddToCart"),
    path('myBasket/', views.myBasketView.as_view(), name ="myBasket"),
    path("manage-cart/<int:cp_id>/", views.ManageCartView.as_view(), name = "managecart"),
    path("checkout/", views.CheckoutView.as_view(), name="checkout"),
    path('myOrders/', views.CustomerOrdersView.as_view(), name ="myOrders"),
    path('cancelOrder<int:pk>', views.CustomerCancelOrdersView.as_view(), name ="cancelOrder"),
    path('myProfile/', views.CustomerProfileView.as_view(), name ="myProfile"),
    path("orderDetails/order-<int:pk>/", views.CustomerOrderDetailView.as_view(),name="customerorderdetail"),
    path('rate-<int:pro_id>/', views.AddToReviewList.as_view(), name ="rate"),
    path("receipt/order-<int:pk>/", views.CustomerReceiptView.as_view(),name="receipt"),
    path("receipt/sendmail/<int:id>", views.SendEmail, name="SendEmail"),
    path('payment/', views.CustomerPaymentView.as_view(), name ="payment"),
    path('myRatingsEvaluated/', views.CustomerReviewView.as_view(), name ="myRatingsEvaluated"),
    path('productReviews/-<int:pk>/', views.ProductReviewView.as_view(), name ="productReviews"),
    path('add_to_wishlist-<int:pro_id>/', views.AddToWishList.as_view(), name = "AddToWishList"),
    path('myWishList/', views.myWishListView.as_view(), name ="myWishList"),
    path('myWishRemove-<int:obj_id>//', views.myWishRemoveView.as_view(), name ="myWishRemove"),



    # PRODUCT MANAGERS URLS
    path("admin-home/", views.productmanagersHome, name="productmanagersHome"),
    path("admin-login/", views.AdminLoginView.as_view(), name="adminlogin"),
    path("admin-PendingOrders/", views.AdminPendingOrdersView.as_view(), name="adminPendingOrders"),
    path("admin-order/<int:pk>/", views.AdminOrderDetailView.as_view(), name="adminorderdetail"),
    path("admin-all-orders/", views.AdminOrderListView.as_view(), name="adminorderlist"),
    path("admin-order-<int:pk>-change/",views.AdminOrderStatusChangeView.as_view(), name="adminorderstatuschange"),
    path("admin-pendingComment/", views.PendingReviewView.as_view(), name="adminpendingComment"),
    path("admin-all-reviews/", views.AdminReviewListView.as_view(), name="adminreviewlist"),
    path("admin-detailComment/<int:pk>/", views.AdminReviewDetailView.as_view(), name="admindetailComment"),
    path("admin-review-<int:pk>-change/",views.AdminReviewStatusChangeView.as_view(), name="adminreviewstatuschange"),
    path("admin-product-list/", views.AdminProductListView.as_view(), name="adminproductlist"),
    path("admin-product-add/", views.AdminProductCreateView.as_view(), name="adminproductcreate"),
    path("admin-productdelete/<int:pr_id>/", views.AdminProductDeleteView.as_view(), name = "adminproductdelete"),
    path("admin-category-list/", views.AdminCategoryListView.as_view(), name="admincategorylist"),
    path("admin-category-add/", views.AdminCategoryCreateView.as_view(), name="admincategorycreate"),
    path("admin-categorydelete/<int:c_id>/", views.AdminCategoryDeleteView.as_view(), name = "admincategorydelete"),
    path("admin-PendingRefundRequests/", views.AdminPendingRefundRequestsView.as_view(), name="adminRefundRequests"),
    path("admin-AllRefundRequests/", views.AdminAllRefundRequestsView.as_view(), name="adminAllRefundRequests"),
    path('product_managers_logout/', views.product_managers_logout, name='product_managers_logout'),
    path('product_managers_stock/<int:pk>/', views.AdminProductStockChangeView.as_view(), name='product_managers_stock'),
    # END OF PRODUCT MANAGERS URLS

    #  SALES MANAGERS URLS
    path("sales-admin-home/", views.salesmanagersHome, name="salesmanagersHome"),
    path("admin-sales-order/<int:pk>/", views.AdminSalesOrderDetailView.as_view(), name="adminsalesorderdetail"),
    path("sales-admin-login/", views.SalesAdminLoginView.as_view(), name="SalesAdminLoginView"),
    path("sales-admin-products/", views.SalesAdminProductListView.as_view(), name="SalesAdminProductListView"),
    path("sales-price-update/<int:id>/change", views.SalesAdminChangePrice, name="SalesAdminChangePrice"),
    path("price_updated/", views.PriceUpdatedView.as_view(), name="PriceUpdatedView"),
    path("sales-show-invoices/", views.SalesShowInvoices.as_view(), name="SalesShowInvoices"),
    path("invoice-pdf/<int:id>", views.ShowPDF, name="ShowPDF"),
    path("sales-show-profit/", views.SalesShowProfit.as_view(), name="SalesShowProfit"),
    path('sales_managers_logout/', views.sales_managers_logout, name='sales_managers_logout'),
    path('sales_managers_price/<int:pk>/', views.AdminProductPriceChangeView.as_view(), name='sales_managers_price'),

    # END OF SALES MANAGERS URLS


    path('otherCategories/', views.OtherCategoryListView.as_view(), name ="OtherCategoryListView"),
    path('allProducts/', views.AllListView.as_view(), name ="AllListView"),
    path('womenDressPage/', views.DressListView.as_view(), name ="DressListView"),
    path('productDetail/<slug>/', views.ProductDetailView.as_view(), name ="productDetail"),
    path('womenSkirtPage/', views.SkirtListView.as_view(), name ="SkirtListView"),
    path('womenSweatshirtPage/', views.SweatshirtListView.as_view(), name ="SweatshirtListView"),
    path('womenBlousesPage/', views.BlousesListView.as_view(), name ="BlousesListView"),
    path('womenSweaterPage/', views.SweaterListView.as_view(), name ="SweaterListView"),
    path('womenTshirtPage/', views.TshirtListView.as_view(), name ="TshirtListView"),
    path('womenCoatPage/', views.CoatListView.as_view(), name ="CoatListView"),
    path('womenSleepPage/', views.SleepListView.as_view(), name ="SleepListView"),
    path('womenShortPage/', views.ShortListView.as_view(), name ="ShortListView"),
    path('womenPantPage/', views.PantListView.as_view(), name ="PantListView"),
    path('womenSweatsuitPage/', views.SweatsuitListView.as_view(), name ="SweatsuitListView"),



    path('user_login/',views.user_login,name='user_login'),
    path('register/', views.register, name ="register"),
    path('myRatings/', views.myRatings, name ="myRatings"),
    path('wishlist/', views.wishlist, name ="wishlist"),


    path('request-refund/order-<int:ord_id>/', views.RequestRefundView.as_view(), name='request-refund'),
    path('grant-refund/orderProduct-<int:orderP_id>/', views.GrantRefundView.as_view(), name='grant-refund')
]

cloth_shop/store/forms.py
from django import forms
from django.contrib.auth.models import User
from django import forms
from .models import Order, OrderProduct
from .models import ReviewItem
from .models import Product
from .models import Category
from django.core.files.uploadedfile import SimpleUploadedFile

# from django_countries.fields import CountryField
# from django_countries.widgets import CountrySelectWidget


class CheckoutForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ["ordered_by", "shipping_address",
                  "email", "payment_method"]


class ProductManagersLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())
    distributor = forms.Select()

class SalesManagersLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())

class PriceChangeForm(forms.Form):

    discount = forms.IntegerField(label='Discount rate')




class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')


class ReviewItemForm(forms.ModelForm):
	class Meta:
		model = ReviewItem
		fields = ["comment", "rate"]

class ContactForm(forms.Form):
    name= forms.CharField(max_length=500, label="Name")
    email= forms.EmailField(max_length=500, label="Email")
    comment= forms.CharField(label='',widget=forms.Textarea(
                        attrs={'placeholder': 'Enter your comment here'}))


class StockForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [ "quantity"]
        widgets = {
            "quantity": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Enter the new quantity in stock..."
            }),

        }


class PriceForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [ "price"]
        widgets = {
            "price": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Enter the new price..."
            }),

        }


class ProductForm(forms.ModelForm):
    more_images = forms.FileField(required=False, widget=forms.FileInput(attrs={
        "class": "form-control",
        "multiple": True
    }))

    class Meta:
        model = Product
        fields = ["name", "gender",  "slug", "category", "Primaryimage", "Secondimage", "Thirdimage", "model", "warrantyStatus",
                   "color", "quantity", "popularity", "price", "description"]
        widgets = {
            "name": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Enter the product title here..."
            }),
            "slug": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Enter the unique slug here..."
            }),
            "gender": forms.Select(attrs={
                "class": "form-control",
            }),
            "category": forms.Select(attrs={
                "class": "form-control"
            }),
             "Primaryimage": forms.FileInput(attrs={
                 "class": "form-control"
             }),
             "Secondimage": forms.ClearableFileInput(attrs={
                 "class": "form-control"
             }),
            "Thirdimage": forms.ClearableFileInput(attrs={
                 "class": "form-control"
             }),
             "price": forms.NumberInput(attrs={
                "class": "form-control",
                "placeholder": "Marked price of the product..."
             }),
            "model": forms.TextInput(attrs={
                "class": "form-control",
            }),
            "description": forms.Textarea(attrs={
                "class": "form-control",
                "placeholder": "Description of the product...",
                "rows": 5
            }),
            "warrantyStatus": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Enter the product warranty here..."
            }),
            "color": forms.TextInput(attrs={
                "class": "form-control",

            }),
            "quantity": forms.TextInput(attrs={
                "class": "form-control",

            }),
            "popularity": forms.TextInput(attrs={
                "class": "form-control",

            }),



         }

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ["name", "slug", "bigcategory" ]
        widgets = {
            "bigcategory": forms.Select(attrs={
                "class": "form-control",
            }),
            "name": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Enter the product title here..."
            }),
            "slug": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Enter the unique slug here..."
            }),

         }

class DateForm(forms.ModelForm):
    start_date = forms.DateTimeField()
    end_date = forms.DateTimeField()
    class Meta:
        model = Order
        fields = []


# class UserProfileInfoForm(forms.ModelForm):
#     class Meta():
#         model = Customer
#         fields = ('adress1','adress2')

cloth_shop/store/templates/productmanagers/adminBase.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />
    <link rel="stylesheet" href="{% static "css/womenDress2.css" %}"/>
    <!-- Bootstrap CSS -->

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="{% static "css/login.css" %}">
    <link rel="stylesheet" href="{% static "css/register.css" %}">
      <link rel="stylesheet" href="{% static "css/base.css" %}">
      <link rel="stylesheet" href="{% static "css/womenNavbar.css" %}"/>
      <link rel="stylesheet" href="{% static "css/womenDress.css" %}"/>
      <link rel="stylesheet" href="{% static "css/product.css" %}"/>
      <link rel="stylesheet" href="{% static "css/womenPage.css" %}"/>
      <link rel="stylesheet" href="{% static "css/myOrders.css" %}"/>
      <link rel="stylesheet" href="{% static "css/orderDetails.css" %}"/>
      <link rel="stylesheet" href="{% static "css/myRating.css" %}"/>
      <link rel="stylesheet" href="{% static "css/myBasket.css" %}"/>
      <link rel="stylesheet" href="{% static "css/checkout.css" %}"/>

    <title>trendSU</title>
    {% block extra_head %}
    {% endblock %}

    <!-- Font Awesome Icons -->
    <script src="https://kit.fontawesome.com/468cba9b63.js" crossorigin="anonymous"></script>

  </head>
  <body>
     <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <img class="trendSU2" src="{% static "images/trendSU2.png" %}" alt="logo">
      <a class = "navbar-brand trend" style="position: relative;left: 10px;">trend<span class ="SU">SU</span></a>
      <ul class = "navbar-nav" style="position: relative;right: 280px;">
        <li class="gender_nav nav-item">
        <a class= "nav-link active" aria-current="page" href="{% url 'store:productmanagersHome' %}">Home</a>
        </li>


        <li class="women_li  nav-item dropdown">
          <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
           Orders
          </a>
          <ul class=" dropdown-menu" aria-labelledby="navbarDropdown">
            <div class="row">
              <div class="col-lg-12">
                <li class="gender_nav nav-item">
                <a class=  "dropdown-item" style="padding-bottom: 10px;padding-top: 10px;" aria-current="page" href="{% url 'store:adminPendingOrders' %}">Pending Orders</a>
                </li>
                <li class="gender_nav nav-item">
                <a class= "dropdown-item" aria-current="page" href="{% url 'store:adminorderlist' %}">All Orders</a>
                </li>
              </div>
            </div>
          </ul>
        </li>

        

        <li class="women_li nav-item dropdown">
          <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
           Reviews
          </a>
          <ul class=" dropdown-menu" aria-labelledby="navbarDropdown">
            <div class="row">
              <div class="col-lg-12">
                <li class="gender_nav nav-item">
                <a class=  "dropdown-item" style="padding-bottom: 10px;padding-top: 10px;" aria-current="page" href="{% url 'store:adminpendingComment' %}">Pending Reviews</a>
                </li>
                <li class="gender_nav nav-item">
                <a class= "dropdown-item" aria-current="page" href="{% url 'store:adminreviewlist' %}">All Reviews</a>
                </li>
              </div>
            </div>
          </ul>
        </li>

        <li class="women_li nav-item dropdown">
          <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
           Products
          </a>
          <ul class=" dropdown-menu" aria-labelledby="navbarDropdown">
            <div class="row">
              <div class="col-lg-12">
                <li class="gender_nav nav-item">
                <a class=  "dropdown-item" style="padding-bottom: 10px;padding-top: 10px;" aria-current="page" href="{% url 'store:adminproductlist' %}">All Products</a>
                </li>
                <li class="gender_nav nav-item">
                <a class= "dropdown-item" aria-current="page" href="{% url 'store:adminproductcreate' %}">Product Add</a>
                </li>
              </div>
            </div>
          </ul>
        </li>

        <li class="women_li nav-item dropdown">
          <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
           Categories
          </a>
          <ul class=" dropdown-menu" aria-labelledby="navbarDropdown">
            <div class="row">
              <div class="col-lg-12">
                <li class="gender_nav nav-item">
                <a class=  "dropdown-item" style="padding-bottom: 10px;padding-top: 10px;" aria-current="page" href="{% url 'store:admincategorylist' %}">All Categories</a>
                </li>
                <li class="gender_nav nav-item">
                <a class= "dropdown-item" aria-current="page"  href="{% url 'store:admincategorycreate' %}">Category Add</a>
                </li>
              </div>
            </div>
          </ul>
        </li>

        <li class="gender_nav nav-item">
        <a class= "nav-link active" aria-current="page" href="{% url 'store:womenPage' %}">Visit trendSU</a>
        </li>

      </ul>

      <ul class="navbar-nav ms-auto" style="position: relative;right: 80px;">
        <li class="second-items nav-item dropdown" style="width: 120px;">
          <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="fas fa-user"></i>  My Admin Account
          </a>
          <ul class=" dropdown-menu" aria-labelledby="navbarDropdown">
            {% if user.is_authenticated %}
            <li class="my_account">
              <div class=" gap-2 col-10 ">
                <a href="{% url 'store:product_managers_logout' %}" class="btn btn-dark btn-sm logout_button"  role="button" style="width: 125px;"> LOGOUT </a></a>
              </div>
            </li>

            {% else %}
            <li class="my_account">
              <div class="d-grid gap-2 col-10 mx-auto">
                <a href="{% url 'store:adminlogin' %}" class="btn btn-dark btn-sm" role="button"> LOG IN </a></a>

              </div>
            </li>

            {% endif %}
          </ul>
        </li>
      </ul>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </nav>

    <!-- END OF NAVIGATION BAR -->





    <div class="container">
        <br>
        {% block content_mainPage %}
        {% endblock  %}
    </div>


    <div class="row">
      <div class="col-lg-2 col-md-2">
        {% block content_SideBar-order %}
        {% endblock %}
      </div>
      <div class="col-lg-10 col-md-10">
        {% block order-page %}
        {% endblock %}
      </div>
    </div>

        {% block extra_scripts %}
        {% endblock extra_scripts %}



    <!-- Option 1: Bootstrap Bundle with Popper -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script> -->


  </body>
</html>

cloth_shop/store/templates/productmanagers/adminHome.html
{% extends 'productmanagers/adminBase.html' %}
{% load static %}

{% block content_mainPage %}

<h1>Welcome to Product Managers Home Page</h1>




{% endblock %}

cloth_shop/store/templates/productmanagers/admincategorylist.html
{% extends 'productmanagers/adminBase.html' %}



{% block content_mainPage %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>All Category list </h3><hr>
            <a href="{% url 'store:admincategorycreate' %}">Add New Category</a>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Category</th>
                        <th>Delete</th>




                    </tr>
                </thead>
                <tbody>
                    {% for p in results %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{p.name}}</td>
                        <td><a href= "{% url 'store:admincategorydelete' p.id %}?action=delete" class="float-end text-black"><i class="fas fa-times"></i></a></td>

                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

cloth_shop/store/templates/productmanagers/admincommentdetail.html
{% extends 'productmanagers/adminBase.html' %}
{% load static %}

{% block content_mainPage %}
<div class="container" style = "margin-bottom: 200px;">

    <div class="row">
        <div class="col-md-9 mx-auto">


            <h3>Review Detail</h3>
            <hr>
            <div class="card order-card mx-auto">
              <h5 class="card-header">
                <div class="row">

                  <div class="date col-3">
                    <p class="order-text">Review ID</p>
                    <div class="row">
                      <div class="col-12">
                        <p class="order-info">Review{{review_obj.id}}</p>
                      </div>
                    </div>
                  </div>
                  <div class="purchaser col-3">
                    <p class="order-text">Review Status</p>
                    <div class="row">
                      <div class="col-12">
                        <p class="order-info">{{review_obj.review_status}}</p>
                      </div>
                    </div>
                  </div>
                  <div class="cost col-3">
                    <p class="order-text">Username</p>
                    <div class="row">
                      <div class="col-12">
                        <p class="order-info">{{review_obj.review_list.customer.user.username}}</p>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="row" style="padding-top: 20px;">
                  <div class="purchaser col-3">
                    <p class="order-text">Email</p>
                    <div class="row">
                      <div class="col-12">
                        <p class="order-info">{{review_obj.review_list.customer.user.email}}</p>
                      </div>
                    </div>
                  </div>
                </div>
              </h5>
              </div>

            <h4>Reviewed Item</h4>
            <table class="table">
                <thead>
                    <tr>

                        <th>Item</th>
                        <th>Rate</th>
                        <th>Comment</th>

                    </tr>
                </thead>
                <tbody>

                    <tr>
                        <td><a target="_blank"
                                href="{% url 'store:productDetail' review_obj.product.slug %}">{{review_obj.product.name}}({{review_obj.product.id}})</a>
                        </td>
                        <td>{{review_obj.rate}}</td>
                        <td>{{review_obj.comment}}</td>

                    </tr>


                </tbody>
            </table>

            <form action="{% url 'store:adminreviewstatuschange' review_obj.id %}" method="POST">
                {% csrf_token %}
                <select name="status" class= "form-control col-3">
                    {% for i, j in allstatus %}
                    <option value="{{i}}" {% if i == review_obj.review_status %}selected{% endif %}>{{j}}</option>
                    {% endfor %}
                </select>
                <button class="btn btn-info" style = "margin-top:20px;">Change</button>

            </form>


        </div>
    </div>
</div>
{% endblock %}

cloth_shop/store/templates/productmanagers/adminproductlist.html
{% extends 'productmanagers/adminBase.html' %}



{% block content_mainPage %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>All Product list for distributor: {{ distributor.name }} </h3><hr>

            <a href="{% url 'store:adminproductcreate' %}">Add New Product</a>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Product ID</th>
                        <th>Product Title</th>
                        <th>Category</th>
                        <th>Image</th>
                        <th>Price</th>
                        <th>Quantity in Stock</th>
                        <th>Delete</th>



                    </tr>
                </thead>
                <tbody>
                    {% for p in results %}
                    <tr>
                        <td>{{p.id}}</td>
                        <td>{{p.name}}</td>
                        <td>{{p.category}}</td>
                        <td><img src= {{p.Primaryimage.url}} style="height: 60px;" alt=""></td>
                        <td>{{p.price}}</td>
                        <td>{{p.quantity}}  <a href= "{% url 'store:product_managers_stock' p.id %}">Change Stock</a></td>
                        <td><a href= "{% url 'store:adminproductdelete' p.id %}?action=delete" class="float-end text-black"><i class="fas fa-times"></i></a></td>


                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}